### ISSUE TITLE
machine with name 'default' not configured

### ISSUE THREAD

**Issue by xenoterracide** [smdahlen/vagrant-hostmanager#102]
`The machine with the name 'default' was not found configured for this Vagrant environment.`

ok... why would I have a default configured? why does vagrant up   error out because of this? what is the resolution?

probably worth noting that  I do have a vm enabled by default. `config.vm.define "oracle", primary: true do |oracle|`

**Comment by danielbenzvi** [comment]
This is caused by obsolete machines that are still in the global Vagrant environment.
Clean it up by running `vagrant global-status --prune`

**Comment by anthonyvipond** [comment]
@danielbenzvi nice

**Comment by rchadha** [comment]
Thanks @danielbenzvi . `vagrant global-status --prune` fixed the issue

**Comment by schmidlorenz** [comment]
@ricoli 's tipp deleting obsolete machines in `./.vagrant/machines` did the trick for me, thank you!

**Comment by hazriqpedia** [comment]
@ricoli 's tip is the solution for me. Thanks!

**Comment by patrick-hill** [comment]
@danielbenzvi Thanks! Got a new alias now: alias vclean='vagrant global-status --prune'

**Comment by 59023g** [comment]
https://github.com/devopsgroup-io/vagrant-hostmanager/issues/21

**Comment by joeapearson** [comment]
I'm finding a similar issue to this.  Maybe worth opening a separate issue.

1. Start work on one Vagrant project with a machine name `project-a`
2. Start work on second project, machine name `project-b`

Project A is now deprecated... and yet I see this occasionally when working with project B:

   The machine with the name 'project-a' was not found configured for
   this Vagrant environment.

Things I've tried:

* `vagrant global-status --prune`.  `vagrant global-status` correctly lists my active VMs as expected.
* `rm -rf ~/.vagrant.d`
* `vboxmanage list vms` gives me sensible output as expected

I'm thinking there must be some sort of cache relating to `project-a` that I haven't managed to clear.  Any ideas?

**Comment by mrtndwrd** [comment]
Would it be possible to include more explanation in the error message? e.g.

"The machine with the name 'default' was not found configured for this Vagrant environment. This might mean that you have old machines in the directory `./.vagrant/machines`" 

And maybe even add 

"Try running `vagrant global-status --prune` to solve the issue"

**Comment by daryn-k** [comment]
please help! `vagrant global-status --prune` didn't solve the problem!

**Comment by mbheemappa** [comment]
I had the same issue and vagrant global-status --prune din't work. 
But later realized that there was an obseleted .vagrant directory, I just deleted that and reissued below command. It just Worked..!!

vagrant global-status --prune

**Comment by martinliu** [comment]
When I install DCOS local mode. I got same problem. 

The machine with the name 'proxy' was not found configured for

I fixed issue and get DCOS vms up and running.

* rm  -rf .vagrant
* vagrant global-status --prune
* vagrant up

**Comment by daminduLiyanage** [comment]
After 3 days trying everything on a Windows machine these steps solved the problem:

Prior to doing carrying out the following make sure the vagrant environment and if you are using the Homestead they are set up in the machine correctly. Instead of trying to get the instance from vagrant Homestead folder you can create a virtual default machine from the PhpStorm itself. 

Goto Tools | vagrant | Init in project root
![image](https://user-images.githubusercontent.com/15995246/36354419-0bbd242c-14a2-11e8-9e4f-3f2e376f8a85.png)
The terminal will open up and a machine named 'default' will be created.
Next, goto Toos | vagrant | up to bring the machine up. 

If it gives you an error, telling it could not determine the machine state or something like that, like what happened in my case open up a separate terminal and run the command 
`$ vagrant global-status --prune`
It will refresh the state of global vagrant machine status. 

Now go to Edit | Settings | Language & Frameworks | PHP then browse the CLI interpreter 
Add interpreter with the + sign to select the 'From Docker, Vagrant, VM, Remote...' to open the vagrant 'configure Remote PHP Interpreter' dialog box
![image](https://user-images.githubusercontent.com/15995246/36354510-a8702e3a-14a3-11e8-81e5-8900672758d6.png)
![image](https://user-images.githubusercontent.com/15995246/36354535-1759cd92-14a4-11e8-9b93-8279b08e122c.png)
The instance folder should be your project folder, it will be there in the text box automatically. 

In here, if it gives an error, informing ssh authentication failed, readd the remote interpreter again. It should solve the problem. Hope this helps!

**Comment by magentomaniac** [comment]
I also needed to remove folder in .vagrant/machines/

**Comment by tdensmore** [comment]
running `vagrant global-status --prune` gave me an error: 

```
/Users/blah/workspace/quickstart/vagrant/Vagrantfile:28:in `fetch': key not found: "admin_password" (KeyError)
	from /Users/blah/workspace/quickstart/vagrant/Vagrantfile:28:in `block (2 levels) in <top (required)>'
```

Trying to delete images was not straightforward either:

I don't have a `.vagrant` folder. I do have a `.vagrant.d` folder. It doesn't contain `machines`, but does contain `boxes`. Deleting the files in this folder did not help.

**Comment by vrubiolo** [comment]
Just to confirm that `vagrant global-status --prune` also did the trick for me. I'd agree a better error message would be welcome as the user it left w/o a clue of what when wrong.

For the record, I had also encountered the issue after changing the machine name in the Vagrantfile.
```
Bringing machine 'test' up with 'libvirt' provider...
==> test: [vagrant-hostmanager:guests] Updating hosts file on active guest virtual machines...
The machine with the name 'nuancier' was not found configured for
this Vagrant environment.
```

**Comment by Maguod** [comment]
If you work in PHPStorm with php frameworks and in console have problem 
"The machine with the name 'machine_name' was not found configured for
this Vagrant environment." In your project this be name machine [http://joxi.ru/GrqWqY6Uk045R2](url)
Remove. And use commanr "vagrant up" Good luck.

**Comment by Maguod** [comment]
> If you work in PHPStorm with php frameworks and in console have problem
> "The machine with the name 'machine_name' was not found configured for
> this Vagrant environment." In your project this be name machine http://joxi.ru/GrqWqY6Uk045R2
> Remove. And use commanr "vagrant up" Good luck.
