### ISSUE TITLE
hostmanager only binding 127.0.0.1 to hostname ?

### ISSUE THREAD

**Issue by adrianmak** [smdahlen/vagrant-hostmanager#118]
project_name = "test"
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.define project_name do |node|
      node.vm.hostname = project_name + ".local"
      node.vm.network "public_network", ip: "192.168.103.130"
  end
  config.vm.provision :hostmanager

I found that the hosts file of host only put
127.0.0.1 test.local

I want it to bind 192.168.103.130 instead

ps windows 8 environment

**Comment by adrianmak** [comment]
Does the above snippet work on Windows host ?
I tried on my Windows, but the hostname still bind on 127.0.0.1

**Comment by davividal** [comment]
In my case, I had to make some minor tweaks on @codeaken 's code for it to work on my case:

```ruby
config.hostmanager.ip_resolver = proc do |machine|
  result = ''.dup
  machine.communicate.execute('/sbin/ifconfig eth2') do |type, data|
    result << data if type == :stdout
  end
  (ip = /inet (addr:)?(\d+\.\d+\.\d+\.\d+)/.match(result)) && ip[2]
end
```

Since I'm using debian, `ifconfig` is not on non-root path, thus `/sbin/ifconfig`.
Also, its output on debian is just `inet IP`, so I made the `addr:` thing optional. Since it is an optional group, I also had to adjust the `ip[2]` thing.

Last bot not least: since I'm using `frozen_string_literal: true` magic comment, I had to turn result into a non-frozen string. `String#dup` does that.
