### ISSUE TITLE
Hosts file does not work on newer versions of OSX

### ISSUE THREAD

**Issue by dpehrson** [smdahlen/vagrant-hostmanager#60]
If I get some time I may work on a pull request for this, but in the meantime I want to get it documented.

Problem: OSX ignores `/etc/hosts` entries unless they are at the TOP of the file.
Solution: Prepend instead of append when adding entries, at least on OSX.
Reference: http://thecoredump.org/2011/09/editing-the-hosts-file-in-mac-os-x-lion/

**Comment by paulcaskey** [comment]
Something here is still messed up. I'm on OSX 10.9.5 and /etc/hosts basically stopped working at some point. I'm not sure when, but it's not due to these issues discussed here. (Many hostnames per line, which dang well SHOULD work, Apple! C'mon now! Why on earth would you mess with that?) (Nor entries only at the "top" of the file.)

I removed these comment lines and IPV6 entries at the top of my file, and now it works. I have no idea what was wrong in here. Maybe I disabled IPv6 on this laptop, and now those entries are invalid. Anyway Apple has clearly introduced many BUGS regarding /etc/hosts.  Fix please! Sheesh! This stuff has worked since 1969! If it ain't broke, .. .. . .. !!!!

Paul

16a17,24
> ##
> # Host Database
> #
> # localhost is used to configure the loopback interface
> # when the system is booting.  Do not change this entry.
> #
> ### 127.0.0.1         www.smartsheet.com
> ### 127.0.0.1         www.facebook.com
17a26,27
> #
> ##
21a32
> #
23a35,41
> # The following lines are desirable for IPv6 capable hosts
> ::1     ip6-localhost ip6-loopback
> fe00::0 ip6-localnet
> ff00::0 ip6-mcastprefix
> ff02::1 ip6-allnodes
> ff02::2 ip6-allrouters
>

**Comment by brmendez** [comment]
@dpehrson This worked. I also tried putting multiple hosts on one line and as you've stated. It does not work. Each host MUST be on it's own line.

Thanks for the help.
